#pragma once

#include <cstddef>

inline constexpr char kProductWebHtml[] =
    "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n  <title>Cardputer Codex Companion</title>\n  <style>:root{font-family:Inter,ui-sans-serif,system-ui;color:#e7edf5;background:#071018;color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 20% 0,#15364b 0,transparent 38%),#071018}header{height:80px;padding:14px 26px;display:flex;align-items:center;justify-content:space"
    "-between;border-bottom:1px solid #294254;background:#08131ddd}h1{font-size:22px;margin:0;letter-spacing:.02em}small{color:#4fd1c5;letter-spacing:.22em}#status{padding:7px 12px;border:1px solid #315266;border-radius:999px;color:#9ee8df}main{display:grid;grid-template-columns:minmax(620px,1fr) 340px;gap:18px;padding:18px}.panel{background:#0d1b27e8;border:1px solid #233b4c;border-radius:16px;box-shadow:0 20px 60px #0005;padding:18px}.toolbar{display:flex;gap:12px;align-items:end;margin-bottom:18px}.toolbar la"
    "bel:first-child{flex:1}label{display:flex;flex-direction:column;gap:6px;color:#a9bbc8;font-size:12px}input,select,textarea,button{font:inherit;color:#e7edf5;background:#101f2c;border:1px solid #345064;border-radius:8px;padding:9px}textarea{min-height:82px;resize:vertical}button{cursor:pointer;background:#172b3a}button:hover{border-color:#4fd1c5}.primary{background:#13776f;border-color:#37afa4}#keyboard{display:grid;grid-template-columns:repeat(14,minmax(35px,1fr));gap:6px}.key{aspect-ratio:1.05;border-radiu"
    "s:7px;padding:4px;font-size:10px;overflow:hidden}.key.active{outline:2px solid #4fd1c5;background:#163d46}.key.mapped{color:#70e1d5}.editor{display:flex;flex-direction:column;gap:12px}.editor h2{font-size:15px;margin:0;color:#dbe8ef}.editor hr{border:0;border-top:1px solid #294253;width:100%}.hint{font-size:11px;line-height:1.5;color:#718b9d}@media(max-width:980px){main{grid-template-columns:1fr}#keyboard{overflow:auto}.editor{width:100%}}\n</style>\n</head>\n<body>\n  <header>\n    <div><small>CARDPUTER</small>"
    "<h1>Codex Companion</h1></div>\n    <span id=\"status\">\u8fde\u63a5\u4e2d</span>\n  </header>\n  <main>\n    <section class=\"panel\">\n      <div class=\"toolbar\">\n        <label>Profile <input id=\"profile-name\" maxlength=\"20\" value=\"CODEX\"></label>\n        <label>Layer <select id=\"layer\"><option>0</option><option>1</option><option>2</option><option>3</option></select></label>\n        <button id=\"reload\">\u91cd\u65b0\u8f7d\u5165</button>\n        <button id=\"publish\" class=\"primary\">\u53d1\u5e03</button>\n      </div>\n      <div id=\"keyboard\" aria-label=\"Cardpu"
    "ter 56-key layout\"></div>\n    </section>\n    <aside class=\"panel editor\">\n      <h2>\u6309\u952e <span id=\"selected-key\">0</span></h2>\n      <label>\u52a8\u4f5c\n        <select id=\"action-kind\">\n          <option value=\"passthrough\">passthrough</option>\n          <option value=\"hid_chord\">hid_chord</option>\n          <option value=\"text_utf8\">text_utf8</option>\n          <option value=\"input_sequence\">input_sequence</option>\n          <option value=\"device_action\">device_action</option>\n          <option value=\"codex_action\">c"
    "odex_action</option>\n          <option value=\"disabled\">disabled</option>\n        </select>\n      </label>\n      <label>\u7ec4\u5408\u952e\u4fee\u9970\u4f4d <input id=\"modifiers\" type=\"number\" min=\"0\" max=\"255\" value=\"0\"></label>\n      <label>HID usages\uff08\u9017\u53f7\u5206\u9694\uff09 <input id=\"usages\" placeholder=\"6,25\"></label>\n      <label>UTF-8 / \u4e2d\u6587\u5b57\u7b26\u4e32 <textarea id=\"text\" maxlength=\"1024\" placeholder=\"\u4f8b\u5982\uff1a\u8bf7\u68c0\u67e5\u8fd9\u6bb5\u4ee3\u7801\"></textarea></label>\n      <label>\u8bbe\u5907\u52a8\u4f5c\n        <select id=\"device-action\">\n          <option value=\"none\">none</option>\n          <option value=\"to"
    "ggle_mode\">toggle_mode</option>\n          <option value=\"open_pairing\">open_pairing</option>\n          <option value=\"reconnect_wifi\">reconnect_wifi</option>\n        </select>\n      </label>\n      <label>Codex \u52a8\u4f5c\n        <select id=\"codex-action\">\n          <option value=\"none\">none</option>\n          <option value=\"select_next\">select_next</option>\n          <option value=\"select_previous\">select_previous</option>\n          <option value=\"interrupt\">interrupt</option>\n          <option value=\"approve\">appr"
    "ove</option>\n          <option value=\"reject\">reject</option>\n        </select>\n      </label>\n      <label>\u5e8f\u5217 JSON <textarea id=\"sequence\" placeholder='[{\"kind\":\"hid_chord\",\"usages\":[6]}]'></textarea></label>\n      <button id=\"apply-key\">\u5e94\u7528\u5230\u6309\u952e</button>\n      <hr>\n      <h2>Wi-Fi \u914d\u7f6e</h2>\n      <label>SSID <input id=\"wifi-ssid\" maxlength=\"32\"></label>\n      <label>\u5bc6\u7801 <input id=\"wifi-password\" type=\"password\" maxlength=\"64\"></label>\n      <button id=\"save-wifi\">\u4fdd\u5b58\u5e76\u91cd\u8fde</button>\n      <p class=\"hint\">\u8bfb\u53d6\u63a5\u53e3\u6c38\u4e0d\u8fd4\u56de Wi"
    "-Fi \u5bc6\u7801\u3002\u5199\u64cd\u4f5c\u9700\u8f93\u5165\u8bbe\u5907\u5c4f\u5e55\u663e\u793a\u7684\u516b\u4f4d\u914d\u5bf9\u7801\u3002</p>\n      <label>\u914d\u5bf9\u7801 <input id=\"pairing-code\" inputmode=\"numeric\" maxlength=\"8\"></label>\n    </aside>\n  </main>\n  <script>const labels=[\"`\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"0\",\"-\",\"=\",\"\u232b\",\"Tab\",\"Q\",\"W\",\"E\",\"R\",\"T\",\"Y\",\"U\",\"I\",\"O\",\"P\",\"[\",\"]\",\"\\\\\",\"Fn\",\"Shift\",\"A\",\"S\",\"D\",\"F\",\"G\",\"H\",\"J\",\"K\",\"L\",\";\",\"'\",\"Enter\",\"Ctrl\",\"Opt\",\"Alt\",\"Z\",\"X\",\"C\",\"V\",\"B\",\"N\",\"M\",\",\",\".\",\"/\",\"Space\"];\nlet profile={name:\"SAFE\",revision:1,bindings:Array.from({length:224},()=>({kind:\"passthrough\"}))},se"
    "lected=0;\nconst $=id=>document.getElementById(id);\nfunction token(){return $(\"pairing-code\").value}\nasync function api(path,options={}){options.headers={...(options.headers||{}),\"X-Cardputer-Pairing\":token(),\"Content-Type\":\"application/json\"};const r=await fetch(path,options);if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}\nfunction bindingIndex(){return Number($(\"layer\").value)*56+selected}\nfunction draw(){const root=$(\"keyboard\");root.innerHTML=\"\";labels.forEach((label,index)=>{c"
    "onst b=document.createElement(\"button\");b.className=\"key\";b.textContent=label;b.dataset.key=index;if(index===selected)b.classList.add(\"active\");if(profile.bindings[bindingIndex()-selected+index]?.kind!==\"passthrough\")b.classList.add(\"mapped\");b.onclick=()=>{selected=index;loadEditor();draw()};root.appendChild(b)})}\nfunction loadEditor(){const a=profile.bindings[bindingIndex()]||{kind:\"passthrough\"};$(\"selected-key\").textContent=`${selected} / ${labels[selected]}`;$(\"action-kind\").value=a.kind||\"passthrough\""
    ";$(\"modifiers\").value=a.modifiers||0;$(\"usages\").value=(a.usages||[]).join(\",\");$(\"text\").value=a.text||\"\";$(\"device-action\").value=a.device||\"none\";$(\"codex-action\").value=a.codex||\"none\";$(\"sequence\").value=a.sequence?JSON.stringify(a.sequence):\"\"}\nfunction applyEditor(){let sequence=[];if($(\"sequence\").value.trim())sequence=JSON.parse($(\"sequence\").value);profile.bindings[bindingIndex()]={kind:$(\"action-kind\").value,modifiers:Number($(\"modifiers\").value),usages:$(\"usages\").value.split(\",\").map(Number).fi"
    "lter(Number.isFinite).slice(0,6),text:$(\"text\").value,device:$(\"device-action\").value,codex:$(\"codex-action\").value,sequence};draw()}\nasync function load(){const state=await api(\"/api/v1/status\");$(\"status\").textContent=`BLE ${state.ble} \u00b7 Wi-Fi ${state.wifi} \u00b7 Mac ${state.companion}`;profile=await api(\"/api/v1/profile\");$(\"profile-name\").value=profile.name;draw();loadEditor()}\n$(\"apply-key\").onclick=()=>{try{applyEditor()}catch(e){alert(e.message)}};$(\"layer\").onchange=()=>{draw();loadEditor()};$(\"reload\")"
    ".onclick=()=>load().catch(e=>alert(e.message));$(\"publish\").onclick=async()=>{applyEditor();profile.name=$(\"profile-name\").value;profile=await api(\"/api/v1/profile\",{method:\"PUT\",body:JSON.stringify(profile)});draw();alert(\"\u5df2\u53d1\u5e03\")};$(\"save-wifi\").onclick=async()=>{await api(\"/api/v1/wifi\",{method:\"POST\",body:JSON.stringify({ssid:$(\"wifi-ssid\").value,password:$(\"wifi-password\").value})});$(\"wifi-password\").value=\"\";alert(\"\u5df2\u4fdd\u5b58\uff0c\u8bbe\u5907\u5c06\u91cd\u8fde\")};\ndraw();load().catch(e=>{$(\"status\").textContent=\"\u9700\u8981\u914d\u5bf9\u7801\";console.warn(e.mes"
    "sage)});\n</script>\n</body>\n</html>\n";
inline constexpr std::size_t kProductWebHtmlSize = sizeof(kProductWebHtml) - 1;
