const labels=["`","1","2","3","4","5","6","7","8","9","0","-","=","⌫","Tab","Q","W","E","R","T","Y","U","I","O","P","[","]","\\","Fn","Shift","A","S","D","F","G","H","J","K","L",";","'","Enter","Ctrl","Opt","Alt","Z","X","C","V","B","N","M",",",".","/","Space"];
let profile={name:"SAFE",revision:1,bindings:Array.from({length:224},()=>({kind:"passthrough"}))},selected=0;
const $=id=>document.getElementById(id);
function token(){return $("pairing-code").value}
async function api(path,options={}){options.headers={...(options.headers||{}),"X-Cardputer-Pairing":token(),"Content-Type":"application/json"};const r=await fetch(path,options);if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
function bindingIndex(){return Number($("layer").value)*56+selected}
function draw(){const root=$("keyboard");root.innerHTML="";labels.forEach((label,index)=>{const b=document.createElement("button");b.className="key";b.textContent=label;b.dataset.key=index;if(index===selected)b.classList.add("active");if(profile.bindings[bindingIndex()-selected+index]?.kind!=="passthrough")b.classList.add("mapped");b.onclick=()=>{selected=index;loadEditor();draw()};root.appendChild(b)})}
function loadEditor(){const a=profile.bindings[bindingIndex()]||{kind:"passthrough"};$("selected-key").textContent=`${selected} / ${labels[selected]}`;$("action-kind").value=a.kind||"passthrough";$("modifiers").value=a.modifiers||0;$("usages").value=(a.usages||[]).join(",");$("text").value=a.text||"";$("device-action").value=a.device||"none";$("codex-action").value=a.codex||"none";$("sequence").value=a.sequence?JSON.stringify(a.sequence):""}
function applyEditor(){let sequence=[];if($("sequence").value.trim())sequence=JSON.parse($("sequence").value);profile.bindings[bindingIndex()]={kind:$("action-kind").value,modifiers:Number($("modifiers").value),usages:$("usages").value.split(",").map(Number).filter(Number.isFinite).slice(0,6),text:$("text").value,device:$("device-action").value,codex:$("codex-action").value,sequence};draw()}
async function load(){const state=await api("/api/v1/status");$("status").textContent=`BLE ${state.ble} · Wi-Fi ${state.wifi} · Mac ${state.companion}`;profile=await api("/api/v1/profile");$("profile-name").value=profile.name;draw();loadEditor()}
$("apply-key").onclick=()=>{try{applyEditor()}catch(e){alert(e.message)}};$("layer").onchange=()=>{draw();loadEditor()};$("reload").onclick=()=>load().catch(e=>alert(e.message));$("publish").onclick=async()=>{applyEditor();profile.name=$("profile-name").value;profile=await api("/api/v1/profile",{method:"PUT",body:JSON.stringify(profile)});draw();alert("已发布")};$("save-wifi").onclick=async()=>{await api("/api/v1/wifi",{method:"POST",body:JSON.stringify({ssid:$("wifi-ssid").value,password:$("wifi-password").value})});$("wifi-password").value="";alert("已保存，设备将重连")};
draw();load().catch(e=>{$("status").textContent="需要配对码";console.warn(e.message)});
