const labels=["`","1","2","3","4","5","6","7","8","9","0","-","=","⌫","Tab","Q","W","E","R","T","Y","U","I","O","P","[","]","\\","Fn","Shift","A","S","D","F","G","H","J","K","L",";","'","Enter","Ctrl","Opt","Alt","Z","X","C","V","B","N","M",",",".","/","Space"];
const actionNames={passthrough:"直通原按键",hid_chord:"组合键",text_utf8:"中文字符串",input_sequence:"输入序列",device_action:"设备动作",codex_action:"Codex 动作",disabled:"禁用"};
const actionSummaryLabel="动作摘要";
const deviceNames={none:"无",toggle_mode:"切换模式",next_profile:"下一个 Profile",previous_profile:"上一个 Profile",open_pairing:"显示 Web PIN",reconnect_wifi:"重连 Wi-Fi"};
const codexNames={none:"无",select_next:"下一个会话",select_previous:"上一个会话",select_next_session:"下一个会话",select_previous_session:"上一个会话",new_session:"新建会话",interrupt:"中断任务",approve:"批准请求",reject:"拒绝请求",provide_input:"提供输入"};
const usageNames={4:"A",5:"B",6:"C",7:"D",8:"E",9:"F",10:"G",11:"H",12:"I",13:"J",14:"K",15:"L",16:"M",17:"N",18:"O",19:"P",20:"Q",21:"R",22:"S",23:"T",24:"U",25:"V",26:"W",27:"X",28:"Y",29:"Z",30:"1",31:"2",32:"3",33:"4",34:"5",35:"6",36:"7",37:"8",38:"9",39:"0",40:"Enter",41:"Esc",42:"Backspace",43:"Tab",44:"Space",45:"-",46:"=",47:"[",48:"]",49:"\\",51:";",52:"'",53:"`",54:",",55:".",56:"/",76:"Delete",79:"→",80:"←",81:"↓",82:"↑"};
const codeToUsage={Enter:40,Escape:41,Backspace:42,Tab:43,Space:44,Minus:45,Equal:46,BracketLeft:47,BracketRight:48,Backslash:49,Semicolon:51,Quote:52,Backquote:53,Comma:54,Period:55,Slash:56,Delete:76,ArrowRight:79,ArrowLeft:80,ArrowDown:81,ArrowUp:82};
let profile={name:"SAFE",revision:1,bindings:Array.from({length:224},()=>({kind:"passthrough"}))};
let profileCatalog=[];
let activeProfileID="SAFE";
let selectedProfileID="";
let selected=0;
let authPin="";
let chordDraft={modifiers:0,usages:[]};
let resultTimer=0;
let setupPoll=0;
const $=id=>document.getElementById(id);
const releaseBase=(document.querySelector('meta[name="release-base-url"]')?.content||"").replace(/\/+$/,"");
function token(){return authPin}
async function api(path,options={}){options.headers={...(options.headers||{}),"X-Cardputer-Pairing":token(),"Content-Type":"application/json"};const r=await fetch(path,options);if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
function profilePath(id){const params=new URLSearchParams();params.set("id",id);return `/api/v1/profile?${params.toString()}`}
function bindingIndex(key=selected){return Number($("layer").value)*56+key}
function cleanAction(action){return action&&action.kind?action:{kind:"passthrough"}}
function stateLabel(value){return ({OK:"正常",OFFLINE:"离线",STARTING:"启动中",ERROR:"错误"}[value]||value||"-")}
function showMicrophoneStatus(microphone={}){$("mic-state").textContent=microphone.state||"-";$("mic-rate").textContent=`${microphone.sample_rate_hz||0} Hz`;$("mic-drop").textContent=`${microphone.drop_percent||0}%`;$("mic-error").textContent=microphone.last_error||"NONE"}
function modifierLabel(mask){const items=[];if(mask&1)items.push("Ctrl");if(mask&2)items.push("Shift");if(mask&4)items.push("Alt");if(mask&8)items.push("Cmd");return items}
function formatChord(modifiers,usages){const parts=modifierLabel(modifiers);(usages||[]).forEach(u=>parts.push(usageNames[u]||`HID ${u}`));return parts.length?parts.join("+"):"未采集"}
function describeAction(action){const a=cleanAction(action);if(a.kind==="passthrough")return "直通";if(a.kind==="hid_chord")return `组合键 ${formatChord(a.modifiers||0,a.usages||[])}`;if(a.kind==="text_utf8")return `文本 ${(a.text||"").slice(0,10)||"空"}`;if(a.kind==="input_sequence")return `序列 ${(a.sequence||[]).length} 步`;if(a.kind==="device_action")return `设备 ${deviceNames[a.device||"none"]||a.device||"无"}`;if(a.kind==="codex_action")return `Codex ${codexNames[a.codex||"none"]||a.codex||"无"}`;if(a.kind==="disabled")return "禁用";return actionNames[a.kind]||a.kind}
function showAuth(){authPin="";selectedProfileID="";$("setup-screen").classList.add("hidden");$("auth-screen").classList.remove("hidden");$("app-shell").classList.add("hidden");$("key-modal").classList.add("hidden");$("status").textContent="未鉴权"}
function showApp(){$("setup-screen").classList.add("hidden");$("auth-screen").classList.add("hidden");$("app-shell").classList.remove("hidden")}
function clientPlatform(){const value=(navigator.userAgentData?.platform||navigator.platform||navigator.userAgent||"").toLowerCase();if(value.includes("win"))return "windows";if(value.includes("mac"))return "macos";return "other"}
async function agentInstallURL(){if(!releaseBase)return "";const response=await fetch(`${releaseBase}/release-manifest.json`,{cache:"no-store"});if(!response.ok)throw new Error("release manifest unavailable");const manifest=await response.json();const platform=clientPlatform();const artifacts=Array.isArray(manifest.artifacts)?manifest.artifacts:[];const match=artifacts.find(item=>item.platform===platform||item.os===platform);if(!match)return "";const target=match.url||match.path||"";return /^https?:\/\//.test(target)?target:`${releaseBase}/${String(target).replace(/^\/+/,"")}`}
async function showAgentInstall(){const link=$("agent-install-link");const note=$("agent-install-note");link.classList.add("hidden");note.classList.add("hidden");try{const url=await agentInstallURL();if(url){link.href=url;link.classList.remove("hidden")}else{note.classList.remove("hidden")}}catch(error){note.classList.remove("hidden");console.warn(error.message)}}
function showSetup(setup){authPin="";$("setup-screen").classList.remove("hidden");$("auth-screen").classList.add("hidden");$("app-shell").classList.add("hidden");const order=["wifi","ble","agent"];const active=setup.step?.startsWith("wifi")?"wifi":setup.step==="ble_pair"?"ble":"agent";order.forEach(name=>{$(`setup-${name}`).classList.toggle("active",name===active);$(`setup-${name}`).classList.toggle("complete",order.indexOf(name)<order.indexOf(active))});const labels={wifi_scan:"正在扫描 Wi-Fi",wifi_select:"请在 Cardputer 上选择 Wi-Fi",wifi_password:"请在 Cardputer 上输入 Wi-Fi 密码",wifi_connect:"正在验证 Wi-Fi 连接",ble_pair:"请从电脑发起蓝牙配对",agent_install:"请安装并启动 Machine Agent"};$("setup-step").textContent=labels[setup.step]||"正在初始化";$("status").textContent=`初始化 · ${setup.version||"-"}`;$("agent-install-link").classList.add("hidden");$("agent-install-note").classList.add("hidden");if(setup.step==="agent_install")showAgentInstall()}
async function probeSetup(){try{const response=await fetch("/api/v1/setup",{cache:"no-store"});if(!response.ok)throw new Error(`${response.status}`);const setup=await response.json();if(setup.complete){showAuth()}else{showSetup(setup)}}catch(error){showSetup({step:"wifi_scan",version:"-"});$("setup-step").textContent="无法读取设备初始化状态"}}
function draw(){const root=$("keyboard");root.innerHTML="";labels.forEach((label,index)=>{const action=cleanAction(profile.bindings[bindingIndex(index)]);const summary=describeAction(action);const button=document.createElement("button");button.type="button";button.className="key";button.dataset.key=index;button.disabled=selectedProfileID==="SAFE";if(action.kind!=="passthrough")button.classList.add("mapped");button.innerHTML=`<strong>${label}</strong><span>${summary}</span>`;button.title=selectedProfileID==="SAFE"?"SAFE 为内置只读 Profile":`${label}: ${summary}`;button.onclick=()=>openKeyModal(index);root.appendChild(button)})}
function setTab(name){$("tab-keyboard").classList.toggle("active",name==="keyboard");$("tab-settings").classList.toggle("active",name==="settings");$("keyboard-view").classList.toggle("hidden",name!=="keyboard");$("settings-view").classList.toggle("hidden",name!=="settings")}
function updateProfileControls(){const selected=profileCatalog.find(item=>item.id===selectedProfileID);const builtin=!selected||selected.builtin||selectedProfileID==="SAFE";const active=selectedProfileID===activeProfileID;$("rename-profile").disabled=builtin;$("delete-profile").disabled=selectedProfileID==="SAFE"||selectedProfileID===activeProfileID;$("activate-profile").disabled=active;$("publish").disabled=builtin;$("profile-name").value=selected?selected.name:profile.name}
function renderProfileCatalog(){const select=$("profile-select");select.innerHTML="";profileCatalog.forEach(item=>{const option=document.createElement("option");option.value=item.id;option.textContent=`${item.name}${item.id===activeProfileID?" · 当前":""}`;select.appendChild(option)});select.value=selectedProfileID;updateProfileControls()}
async function loadSelectedProfile(){profile=await api(profilePath(selectedProfileID));$("profile-name").value=profile.name;updateProfileControls();draw()}
async function loadProfileCatalog(preferred){const catalog=await api("/api/v1/profiles");profileCatalog=Array.isArray(catalog.profiles)?catalog.profiles:[];activeProfileID=catalog.active_id||"SAFE";const available=id=>profileCatalog.some(item=>item.id===id);selectedProfileID=available(preferred)?preferred:(available(activeProfileID)?activeProfileID:"SAFE");renderProfileCatalog();await loadSelectedProfile()}
async function load(){const state=await api("/api/v1/status");$("status").textContent=`BLE ${stateLabel(state.ble)} · Wi-Fi ${stateLabel(state.wifi)} · Mac ${stateLabel(state.companion)}`;showMicrophoneStatus(state.microphone);await loadProfileCatalog(selectedProfileID)}
async function authenticate(event){event.preventDefault();const pin=$("login-pin").value.trim();$("auth-error").textContent="";if(!/^[0-9]{8}$/.test(pin)){$("auth-error").textContent="请输入 8 位数字 PIN";return}authPin=pin;try{await load();showApp();setTab("keyboard")}catch(error){authPin="";$("auth-error").textContent="PIN 错误或设备不可达";console.warn(error.message)}}
function keyUsage(event){if(event.code&&event.code.startsWith("Key"))return event.code.charCodeAt(3)-65+4;if(event.code&&event.code.startsWith("Digit")){const digit=Number(event.code.slice(5));return digit===0?39:29+digit}return codeToUsage[event.code]||0}
function captureChord(event){event.preventDefault();event.stopPropagation();const usage=keyUsage(event);if(!usage){$("chord-capture").value="不支持这个键，请换一个普通键";return}let modifiers=0;if(event.ctrlKey)modifiers|=1;if(event.shiftKey)modifiers|=2;if(event.altKey)modifiers|=4;if(event.metaKey)modifiers|=8;chordDraft={modifiers,usages:[usage]};$("modifiers").value=String(modifiers);$("usages").value=String(usage);$("chord-capture").value=formatChord(modifiers,[usage])}
function setEditorVisibility(){const kind=$("action-kind").value;$("chord-fields").classList.toggle("hidden",kind!=="hid_chord");$("text-fields").classList.toggle("hidden",kind!=="text_utf8");$("sequence-fields").classList.toggle("hidden",kind!=="input_sequence");$("device-fields").classList.toggle("hidden",kind!=="device_action");$("codex-fields").classList.toggle("hidden",kind!=="codex_action")}
function loadEditor(){const action=cleanAction(profile.bindings[bindingIndex()]);$("selected-key").textContent=`Layer ${$("layer").value} · 键位 ${selected} / ${labels[selected]} · 当前：${describeAction(action)}`;$("action-kind").value=action.kind||"passthrough";chordDraft={modifiers:action.modifiers||0,usages:action.usages||[]};$("modifiers").value=String(chordDraft.modifiers);$("usages").value=chordDraft.usages.join(",");$("chord-capture").value=formatChord(chordDraft.modifiers,chordDraft.usages);$("text").value=action.text||"";$("device-action").value=action.device||"none";$("codex-action").value=action.codex||"none";$("sequence").value=action.sequence?JSON.stringify(action.sequence):"";setEditorVisibility()}
function openKeyModal(index){selected=index;$("key-save-error").textContent="";loadEditor();$("key-modal").classList.remove("hidden");$("modal-title").textContent=`修改按键 ${labels[index]}`}
function closeKeyModal(){$("key-modal").classList.add("hidden")}
function closeResult(){if(resultTimer){clearTimeout(resultTimer);resultTimer=0}$("result-modal").classList.add("hidden")}
function showResult(kind,message){closeResult();const success=kind==="success";$("result-title").textContent=success?"修改成功":"修改失败";$("result-message").textContent=message;$("result-card").classList.toggle("result-success",success);$("result-card").classList.toggle("result-error",!success);$("result-modal").classList.remove("hidden");if(success)resultTimer=setTimeout(closeResult,1500);else $("result-close").focus()}
function readEditorAction(){const kind=$("action-kind").value;let action={kind};if(kind==="hid_chord"){action.modifiers=chordDraft.modifiers;action.usages=chordDraft.usages.slice(0,6)}else if(kind==="text_utf8"){action.text=$("text").value}else if(kind==="input_sequence"){action.sequence=$("sequence").value.trim()?JSON.parse($("sequence").value):[]}else if(kind==="device_action"){action.device=$("device-action").value}else if(kind==="codex_action"){action.codex=$("codex-action").value}return action}
async function applyEditor(event){event.preventDefault();const index=bindingIndex();const previous=profile.bindings[index];$("key-save-error").textContent="";$("apply-key").disabled=true;$("delete-mapping").disabled=true;try{profile.bindings[index]=readEditorAction();await publishProfile(false);closeKeyModal();showResult("success","键位配置已发布到设备")}catch(error){profile.bindings[index]=previous;$("key-save-error").textContent=error.message;showResult("error",`修改失败：${error.message}`)}finally{$("apply-key").disabled=false;$("delete-mapping").disabled=false}}
async function restorePassthrough(){const index=bindingIndex();const previous=profile.bindings[index];$("key-save-error").textContent="";$("apply-key").disabled=true;$("delete-mapping").disabled=true;profile.bindings[index]={kind:"passthrough"};try{await publishProfile(false);closeKeyModal();showResult("success","键位已恢复直通并发布到设备")}catch(error){profile.bindings[index]=previous;$("key-save-error").textContent=error.message;showResult("error",`修改失败：${error.message}`)}finally{$("apply-key").disabled=false;$("delete-mapping").disabled=false}}
async function publishProfile(announce=true){if(selectedProfileID==="SAFE")throw new Error("SAFE 为内置只读 Profile");profile=await api(profilePath(selectedProfileID),{method:"PUT",body:JSON.stringify(profile)});await loadProfileCatalog(selectedProfileID);if(announce)showResult("success","键盘配置已发布到设备");return profile}
async function createProfile(clone){const selected=profileCatalog.find(item=>item.id===selectedProfileID);const fallback=clone&&selected?`${selected.name} 副本`:"新 Profile";const name=prompt(clone?"输入克隆 Profile 名称":"输入新 Profile 名称",fallback);if(name===null)return;const trimmed=name.trim();if(!trimmed||trimmed.length>20){showResult("error","Profile 名称必须为 1–20 个字符");return}try{const body={name:trimmed};if(clone)body.clone_id=selectedProfileID;const created=await api("/api/v1/profiles",{method:"POST",body:JSON.stringify(body)});await loadProfileCatalog(created.id);showResult("success",clone?"Profile 已克隆":"Profile 已创建")}catch(error){showResult("error",`操作失败：${error.message}`)}}
async function renameProfile(){if(selectedProfileID==="SAFE")return;const name=prompt("输入新的 Profile 名称",profile.name);if(name===null)return;const trimmed=name.trim();if(!trimmed||trimmed.length>20){showResult("error","Profile 名称必须为 1–20 个字符");return}const previous=profile.name;profile.name=trimmed;try{await publishProfile(false);showResult("success","Profile 已重命名")}catch(error){profile.name=previous;showResult("error",`重命名失败：${error.message}`)}}
async function activateProfile(){try{await api("/api/v1/profile/activate",{method:"POST",body:JSON.stringify({id:selectedProfileID})});await loadProfileCatalog(selectedProfileID);showResult("success","当前键盘 Profile 已切换")}catch(error){showResult("error",`切换失败：${error.message}`)}}
async function deleteProfile(){if(selectedProfileID==="SAFE"){showResult("error","SAFE 为内置 Profile，不能删除");return}if(selectedProfileID===activeProfileID){showResult("error","当前 Profile 不能删除，请先激活 SAFE");return}const selected=profileCatalog.find(item=>item.id===selectedProfileID);if(!confirm(`确认删除 Profile「${selected?selected.name:selectedProfileID}」？`))return;try{await api(profilePath(selectedProfileID),{method:"DELETE"});await loadProfileCatalog(activeProfileID);showResult("success","Profile 已删除")}catch(error){showResult("error",`删除失败：${error.message}`)}}
async function saveWifi(event){event.preventDefault();await api("/api/v1/wifi",{method:"POST",body:JSON.stringify({ssid:$("wifi-ssid").value,password:$("wifi-password").value})});$("wifi-password").value="";alert("已保存，设备将重连")}
async function savePin(event){event.preventDefault();const pin=$("new-pin").value.trim();const confirmation=$("confirm-pin").value.trim();if(!/^[0-9]{8}$/.test(pin)){showResult("error","PIN 必须是 8 位数字");return}if(pin!==confirmation){showResult("error","两次输入的 PIN 不一致");return}try{await api("/api/v1/pin",{method:"POST",body:JSON.stringify({pin})});authPin=pin;$("login-pin").value=pin;$("new-pin").value="";$("confirm-pin").value="";showResult("success","PIN 已修改，Mac Agent 将自动迁移")}catch(error){showResult("error",`PIN 修改失败：${error.message}`)}}
async function restartSetup(){if(!confirm("确认重新运行初始化向导？现有配置不会自动删除。"))return;try{await api("/api/v1/setup/restart",{method:"POST",body:JSON.stringify({confirm:"RUN_SETUP_AGAIN"})});await probeSetup()}catch(error){showResult("error",`无法重新运行初始化：${error.message}`)}}
$("pin-form").onsubmit=authenticate;$("tab-keyboard").onclick=()=>setTab("keyboard");$("tab-settings").onclick=()=>setTab("settings");$("logout").onclick=showAuth;$("restart-setup").onclick=restartSetup;$("layer").onchange=draw;$("profile-select").onchange=()=>{selectedProfileID=$("profile-select").value;loadSelectedProfile().catch(error=>showResult("error",`载入失败：${error.message}`))};$("create-profile").onclick=()=>createProfile(false);$("clone-profile").onclick=()=>createProfile(true);$("rename-profile").onclick=renameProfile;$("activate-profile").onclick=activateProfile;$("delete-profile").onclick=deleteProfile;$("reload").onclick=()=>loadProfileCatalog(selectedProfileID).catch(e=>showResult("error",e.message));$("publish").onclick=()=>publishProfile().catch(e=>showResult("error",e.message));$("wifi-form").onsubmit=e=>saveWifi(e).catch(error=>alert(error.message));$("change-pin").onsubmit=e=>savePin(e).catch(error=>alert(error.message));$("key-form").onsubmit=applyEditor;$("close-modal").onclick=closeKeyModal;$("delete-mapping").onclick=restorePassthrough;$("result-close").onclick=closeResult;$("action-kind").onchange=setEditorVisibility;$("chord-capture").onkeydown=captureChord;probeSetup();setupPoll=setInterval(()=>{if(!$("setup-screen").classList.contains("hidden"))probeSetup()},2000);
